[build]
  command = "eleventy" # Or "npx @11ty/eleventy" if Eleventy is a local dependency
  publish = "_site"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 200
