backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "index.html"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Hero Text", name: "hero", widget: "text" }

  - name: "products"
    label: "Our Products"
    folder: "pages/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }

